# Site settings
title: Justin Plasmeier
description: Justin Plasmeier's blog
favicon: /assets/img/avatar.png
url: http://jplaz.com
baseurl: /resume
rss_url: /pages/atom.xml
cdn_path: https://dl.dropboxusercontent.com/u/76914999

# Build settings
markdown: kramdown
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

# Author settings
author:
  name: Justin Plasmeier
  title: Computer Science and Mathematics Student
  address: Cleveland, Ohio
  email: jplasmeier@gmail.com
  link: https://jplaz.com
  weibo:
  github: justinplasmeier
  linkedin: jplasmeier
  twitter: justinplasmeier
  blog: https://jplaz.com
  resume: https://jplaz.com/resume/PrintResume.pdf
  gavatar:                   
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: German
      proficiency: Professional
  skills:
    - entity:
      category: strongLanguages
    - entity:
      category: weakLanguages
    - entity:
      category: strongSoftware
    - entity:
      category: weakSoftware
  strongLanguages:
    - lang: "C#"
      info: "At Answers I used C# to develop a data migration tool to automate importing product information from SQL to our web app. At Concur, I used C# to develop the new Travel Profile page and to create a browser testing automation framework with automatic test generation capabilities."
    - lang: Java
      info: I've worked with Java projects of all sizes, including enterprise. 
    - lang: SQL/T-SQL
      info: At Answers, I used SQL nearly every day to access product data. For one of the projects I worked on, I wrote a comprehensive stored procedure in T-SQL to automate a tedious data feed import.
    - lang: "Python"
      info: I have used Python at Concepts Collective to build web applications, as well as in various other projects that I have worked on.
    - lang: CSS
      info: At Answers, I developed application features and wrote CSS to incorporate user interactive elements of the featres in the user interface. I also wrote additional CSS to modify the template of this resume. 
    - lang: HTML5
      info: Throughout my experience with web development I have made use of HTML. For this resume, I have used Jekyll, Markdown, and Liquid to parse information into HTML.
    - lang: Javascript
      info: "At Answers, I used Javascript to help implement features along with jQuery to make calls in a Model-View-Controller environment in an existing web application."
  weakLanguages:
    - lang: C
      info: I have used some C for small projects and am learning more about C in my Operating Systems class. 
    - lang: Perl 
      info: I used Perl at Concur to automatically generate test cases within the browser testing automation project. By parsing the abstract classes and taking browser choices as input, we avoided having to manually write test cases resulting in an order of magnitude of better test coverage than what would have been possible manually.
    - lang: "MATLAB"
      info: I used MATLAB to write routines in my Scientific Computing class to approximate integrals, differentiation, and to solve differential equations within a theoretical error bound.
  strongSoftware:
    - lang: Windows
      info: I have been using Windows computers for as long as I can remember, and have used some of the more advanced features at Student Affairs IT.
    - lang: Linux
      info: I have experience using Linux and have set up many differently configured Linux machines. I have experience with bash and am comfortable working in the CLI environment.
    - lang: Jekyll
      info: This resume uses Jekyll. The original template did not actually make use of the posts system in Jekyll, so I rewrote the HTML to actually use posts and Markdown.
    - lang: Microsoft SQL Server
      info: At Answers, I used Microsoft SQL Server to connect to databases, write queries, and preform jobs.
    - lang: Git
      info: I have used Git for version control for years. It's great. 
    - lang: Agile/Scrum
      info: At Answers, my team used Agile and Scrum to manage application development. I participated in MWF standups and biweekly sprint review meetings.
    - lang: Visual Studio
      info: All of the development work I did at Answers and Concur aside from SQL took place within Visual Studio. 
  weakSoftware:
    - lang: Mac OS X
      info: "I am proficient at using Mac OS X, though I haven't used many of the more advanced features."
    - lang: Beaker
      info: I have played around with TwoSigma's Beaker notebook and used it to replace boilerplate file reading and writing in homework assignments.
    - lang: SVN
      info: My team at Concur used SVN, but I much prefer Git.
    - lang: Selenium
      info: The browser testing automation project that I developed at Concur used WebDriver to run tests against the UI. Most of my work dealt with the architecture around the test cases rather than the actual tests.
  otherInterests:
    - interest1:
      name: Ultimate Frisbee
      icon: sport
      info: I started playing Ultimate at Case and have loved every minute of it. I have played for the Cleveland Mixed team and currently play for the CWRU Fighting Gobies. 
    - interest2:
      name: Soccer
      icon: sport
      info: I've been playing soccer for most of my ambulatory life and am always up for a game. 
    - interest3:
      name: Physics
      icon: science
      info: I love learning about ideas and concepts in Physics, especially special and general relativity, quantum mechaincs, and quantum cosmology. 
    - interest4:
      name: Philosophy
      icon: book
      info: I enjoy reading books about the philosophy of the mind, mathematics, and language. My favorite authors lately have been Buckminster Fuller and Ludwig Wittgenstein.
