# Site settings
title: Justin Plasmeier
description: Justin Plasmeier's blog
favicon: /assets/img/avatar.png
baseurl: /iCard-Resume
url: https://justinplasmeier.herokuapp.com
rss_url: /pages/atom.xml
cdn_path: https://dl.dropboxusercontent.com/u/76914999

# Build settings
markdown: kramdown
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

# Author settings
author:
  name: Justin Plasmeier
  title: Math and Computer Science Dual Degree Student
  address: Cleveland, Ohio
  email: jplasmeier@gmail.com
  link: http://jplaz.com
  weibo:
  github: justinplasmeier
  linkedin: jplasmeier
  twitter:
  gavatar:                   
      # * Implemented and tested a phonebook abstract data type using LinkedList and ArrayList
      #  * Designed, implemented, and tested a Huffman encoder using binary trees to encode text files
      #    * Designed, implemented, and tested a custom hash table to count word occurrence and length
       #       * Implemented and analytically compared various sorting algorithms under different test cases
       #         * Implemented numerous algorithms for determining matrix decomposition, polynomial interpolation, numerical differentiation and integration, and solutions of differential equations
       #           * Proved error bounds analytically and verified these results programatically in MATLAB
       #             * Computed algorithm efficiency in flops and Big-O notation
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: German
      proficiency: Professional
  skills:
    - entity:
      category: strongLanguages
    - entity:
      category: weakLanguages
    - entity:
      category: strongSoftware
    - entity:
      category: weakSoftware
  strongLanguages:
    - lang: "C#"
      info: "At Answers, I built a Windows Forms application from scratch in C# to interface with a SQL database and conditionally restrict data using logical expressions based on the SQL schema. Additionally, I repaired a C# application to safely retry a data fetch operation"
    - lang: Java
      info: I've used Java in both Intro to Programming and Intro to Data Structures. In Data Strucutures, I designed, implemented, and tested a Huffman encoder using binary trees to encode text files. I also designed, implemented, and tested a custom hash table to count word occurrence and length. I implemented and analytically compared various sorting algorithms under different test cases.
    - lang: SQL/T-SQL
      info: At Answers, I used SQL nearly every day to access product data. For one of the projects I worked on, I wrote a comprehensive stored procedure in T-SQL to automate a tedious data feed import.
    - lang: CSS
      info: At Answers, I developed application features and wrote CSS rules to incorporate user interactive elements of the featres in the user interface. I also wrote additional CSS rules to modify the template of this resume. 
    - lang: HTML
      info: Throughout my experience with web development I have made use of HTML. For this resume, I have used Jekyll, Markdown, and Liquid to parse information into HTML.
    - lang: Javascript
      info: At Asnwers, I used Javascript to help implement application features. 
  weakLanguages:
    - lang: C
    - lang: "Python"
    - lang: Swift
    - lang: "MATLAB"
  strongSoftware:
    - lang: Windows
    - lang: Linux
    - lang: Jekyll
    - lang: Microsoft SQL Server
    - lang: Visual Studio
    - lang: Adobe Illustrator
  weakSoftware:
    - lang: Node.js
    - lang: Mac OS X
    - lang: Adobe Photoshop
    - lang: AutoCAD
  otherInterests:
    - interest1:
      name: Ultimate Frisbee
      icon: sport
    - interest2:
      name: Soccer
      icon: sport
    - interest3:
      name: Physics
      icon: science
    - interest4:
      name: Philosophy
      icon: book

