# Site settings
title: Justin Plasmeier
description: Justin Plasmeier's blog
favicon: /assets/img/avatar.png
baseurl: /iCard-Resume
url: https://justinplasmeier.herokuapp.com
rss_url: /pages/atom.xml
cdn_path: https://dl.dropboxusercontent.com/u/76914999

# Build settings
markdown: kramdown
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

# Author settings
author:
  name: Justin Plasmeier
  title: Math and Computer Science Dual Degree Student
  address: Cleveland, Ohio
  email: jplasmeier@gmail.com
  link: http://jplaz.com
  weibo:
  github: justinplasmeier
  linkedin: jplasmeier
  twitter:
  gavatar:                   
      # * Implemented and tested a phonebook abstract data type using LinkedList and ArrayList
      #  * Designed, implemented, and tested a Huffman encoder using binary trees to encode text files
      #    * Designed, implemented, and tested a custom hash table to count word occurrence and length
       #       * Implemented and analytically compared various sorting algorithms under different test cases
       #         * Implemented numerous algorithms for determining matrix decomposition, polynomial interpolation, numerical differentiation and integration, and solutions of differential equations
       #           * Proved error bounds analytically and verified these results programatically in MATLAB
       #             * Computed algorithm efficiency in flops and Big-O notation
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: German
      proficiency: Professional
  skills:
    - entity:
      category: strongLanguages
    - entity:
      category: weakLanguages
    - entity:
      category: strongSoftware
    - entity:
      category: weakSoftware
  strongLanguages:
    - lang: "C#"
    - lang: Java
    - lang: SQL/T-SQL
    - lang: CSS
    - lang: HTML
    - lang: Javascript
  weakLanguages:
    - lang: C
    - lang: Python
    - lang: Swift
    - lang: MATLAB
    - lang: Ruby
  strongSoftware:
    - lang: Windows
    - lang: Linux
    - lang: Jekyll
    - lang: Microsoft SQL Server
    - lang: Visual Studio
    - lang: Adobe Illustrator
  weakSoftware:
    - lang: Mac OS X
    - lang: Adobe Photoshop
    - lang: AutoCAD
  otherInterests:
    - interest1:
      name: Ultimate Frisbee
      icon: sport
    - interest2:
      name: Soccer
      icon: sport
    - interest3:
      name: Physics
      icon: science
    - interest4:
      name: Philosophy
      icon: book

