# Site settings
title: Justin Plasmeier
description: Justin Plasmeier's blog
favicon: /assets/img/avatar.png
baseurl: /iCard-Resume
url: https://justinplasmeier.herokuapp.com
rss_url: /pages/atom.xml
cdn_path: https://dl.dropboxusercontent.com/u/76914999

# Build settings
markdown: kramdown
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

# Author settings
author:
  name: Justin Plasmeier
  title: Math and Computer Science Dual Degree Student
  address: Cleveland, Ohio
  email: jplasmeier@gmail.com
  link: http://jplaz.com
  weibo:
  github: justinplasmeier
  linkedin: jplasmeier
  twitter:
  gavatar:                   
      # * Implemented and tested a phonebook abstract data type using LinkedList and ArrayList
      #  * Designed, implemented, and tested a Huffman encoder using binary trees to encode text files
      #    * Designed, implemented, and tested a custom hash table to count word occurrence and length
       #       * Implemented and analytically compared various sorting algorithms under different test cases
       #         * Implemented numerous algorithms for determining matrix decomposition, polynomial interpolation, numerical differentiation and integration, and solutions of differential equations
       #           * Proved error bounds analytically and verified these results programatically in MATLAB
       #             * Computed algorithm efficiency in flops and Big-O notation
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: German
      proficiency: Professional
  skills:
    - entity:
      category: strongLanguages
    - entity:
      category: weakLanguages
    - entity:
      category: strongSoftware
    - entity:
      category: weakSoftware
  strongLanguages:
    - lang: "C#"
      info: "At Answers, I built a Windows Forms application from scratch in C# to interface with a SQL database and conditionally restrict data using logical expressions based on the SQL schema. Additionally, I repaired a C# application to safely retry a data fetch operation"
    - lang: Java
      info: I've used Java in both Intro to Programming and Intro to Data Structures. In Data Strucutures, I designed, implemented, and tested a Huffman encoder using binary trees to encode text files. I also designed, implemented, and tested a custom hash table to count word occurrence and length. I implemented and analytically compared various sorting algorithms under different test cases.
    - lang: SQL/T-SQL
      info: At Answers, I used SQL nearly every day to access product data. For one of the projects I worked on, I wrote a comprehensive stored procedure in T-SQL to automate a tedious data feed import.
    - lang: "Python"
      info: I have used Python at Concepts Collective to build web applications, as well as in various other projects that I have worked on.
    - lang: "Hadoop"
      info: In my Independent Study with a Case Medical School professor working in Medical Informatics, I configured Hadoop clusters and implemented MapReducde and Pig code on the clusters.
    - lang: CSS
      info: At Answers, I developed application features and wrote CSS to incorporate user interactive elements of the featres in the user interface. I also wrote additional CSS to modify the template of this resume. 
    - lang: HTML5
      info: Throughout my experience with web development I have made use of HTML. For this resume, I have used Jekyll, Markdown, and Liquid to parse information into HTML.
    - lang: Javascript
      info: "At Answers, I used Javascript to help implement features along with jQuery to make calls in a Model-View-Controller environment in an existing web application."
  weakLanguages:
    - lang: C
      info: I have used some C for small projects and am learning more about C in my Operating Systems class. 
    - lang: Swift
      info: "I have completed some tutorials about Swift and iOS App Development, but I haven't done anything significant on my own."
    - lang: "MATLAB"
      info: I used MATLAB to write routines in my Scientific Computing class to approximate integrals, differentiation, and to solve differential equations within a theoretical error bound.
  strongSoftware:
    - lang: Windows
      info: I have been using Windows computers for as long as I can remember, and have used some of the more advanced features at Student Affairs IT.
    - lang: Linux
      info: I have experience using Linux and have set up many differently configured Linux machines. I have experience with bash and am comfortable working in the CLI environment.
    - lang: Jekyll
      info: This resume uses Jekyll. The original template did not actually make use of the posts system in Jekyll, so I rewrote the HTML to actually use posts and Markdown.
    - lang: Microsoft SQL Server
      info: At Answers, I used Microsoft SQL Server to connect to databases, write queries, and preform jobs.
    - lang: Git
      info: At Answers, I learned how to use Git for version control, and have used it for all of my projects since.
    - lang: Agile/Scrum
      info: At Answers, my team used Agile and Scrum to manage application development. I participated in MWF standups and biweekly sprint review meetings.
    - lang: Visual Studio
      info: All of the development work I did at Answers outside of SQL took place within Visual Studio. 
    - lang: Adobe Illustrator
      info: At Student Affairs IT, I used Adobe Illustrator to create logo elements and edit existing maps. I have also used Illustrator to create graphics for personal projects.
  weakSoftware:
    - lang: Node.js
      info: I am currently working through the Nodeschool workshops, and have attended Meetups for Nodeschool.
    - lang: React
      info: I have been learning React and have started working on a larger project to hone my skills with React.
    - lang: Mac OS X
      info: "I am proficient at using Mac OS X, though I haven't used many of the more advanced features."
    - lang: Adobe Photoshop
      info: I have used Photoshop for many small projects, and am comfortable using Photoshop to edit images and other simpler tasks.
    - lang: AutoCAD
      info: I took a very comprehensive AutoCAD class in High School and have some outside experience with mechanical drawing. 
  otherInterests:
    - interest1:
      name: Ultimate Frisbee
      icon: sport
      info: I started playing Ultimate at Case and have loved every minute of it. I have played for the Cleveland Mixed team and currently play for the CWRU Fighting Gobies. 
    - interest2:
      name: Soccer
      icon: sport
      info: I've been playing soccer for most of my ambulatory life and am always up for a game. 
    - interest3:
      name: Physics
      icon: science
      info: I love learning about ideas and concepts in Physics, especially special and general relativity, quantum mechaincs, and quantum cosmology. 
    - interest4:
      name: Philosophy
      icon: book
      info: I enjoy reading books about the philosophy of the mind, mathematics, and language. My favorite authors lately have been Buckminster Fuller and Ludwig Wittgenstein.
    - interest5:
      name: Investing
      icon: money
      info: I have a considerable portion of my savings invested in the stock market. I have traded stocks at weekly frequency but have since switched primarily to index funds for ease of management. I would like to learn more about Computational Investing.

